ALTER TABLE `sources` ADD `open_access_url` text;
ALTER TABLE `sources` ADD `content_scope` text DEFAULT 'metadata' NOT NULL;
ALTER TABLE `sources` ADD `fulltext_status` text DEFAULT 'metadata_only' NOT NULL;
ALTER TABLE `sources` ADD `sync_error` text;
ALTER TABLE `sources` ADD `collection` text DEFAULT 'official' NOT NULL;
ALTER TABLE `sources` ADD `orcid` text;
ALTER TABLE `sources` ADD `cited_by_count` integer;
ALTER TABLE `sources` ADD `citation_provider` text;
ALTER TABLE `sources` ADD `abstract` text;
ALTER TABLE `chunks` ADD `language` text DEFAULT 'en' NOT NULL;
ALTER TABLE `chunks` ADD `page_number` integer;
ALTER TABLE `chunks` ADD `content_hash` text;
ALTER TABLE `chunks` ADD `vector_version` text;
CREATE VIRTUAL TABLE IF NOT EXISTS `chunks_fts` USING fts5(`chunk_id` UNINDEXED, `source_id` UNINDEXED, `title`, `section`, `content`, tokenize='unicode61 remove_diacritics 2');
CREATE TABLE `visitor_usage` (`visitor_hash` text NOT NULL, `day` text NOT NULL, `generated_count` integer DEFAULT 0 NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `idx_visitor_usage_hash_day` ON `visitor_usage` (`visitor_hash`,`day`);
CREATE TABLE `global_usage` (`day` text PRIMARY KEY NOT NULL, `generated_count` integer DEFAULT 0 NOT NULL, `input_tokens` integer DEFAULT 0 NOT NULL, `output_tokens` integer DEFAULT 0 NOT NULL, `updated_at` text NOT NULL);
CREATE TABLE `rag_requests` (`id` text PRIMARY KEY NOT NULL, `visitor_hash` text NOT NULL, `mode` text NOT NULL, `status` text NOT NULL, `retrieval_mode` text NOT NULL, `input_tokens` integer DEFAULT 0 NOT NULL, `output_tokens` integer DEFAULT 0 NOT NULL, `latency_ms` integer NOT NULL, `created_at` text NOT NULL, `error_code` text);
CREATE INDEX `idx_rag_requests_created_at` ON `rag_requests` (`created_at`);
CREATE TABLE `system_state` (`key` text PRIMARY KEY NOT NULL, `value` text NOT NULL, `updated_at` text NOT NULL);
CREATE TABLE `rate_limit_events` (`visitor_hash` text NOT NULL, `minute_bucket` text NOT NULL, `request_count` integer DEFAULT 0 NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `idx_rate_limit_events_hash_minute` ON `rate_limit_events` (`visitor_hash`,`minute_bucket`);
PRAGMA optimize;
