import type { EvaluationRun, SearchResult, Source } from "./types";
import { ORCID_ADDITIONAL_SOURCES } from "./lab-works";

export const DEMO_SOURCES: Source[] = [
  { id:"ethereum-whitepaper", title:"Ethereum Whitepaper", url:"https://ethereum.org/en/whitepaper/", topic:"foundation", type:"official_docs", authors:["Vitalik Buterin"], year:2014, license:"CC BY 4.0", status:"published", lastSyncedAt:"2026-08-13T09:00:00Z", collection:"official" },
  { id:"solidity-security", title:"Solidity Documentation — Security Considerations", url:"https://docs.soliditylang.org/en/latest/security-considerations.html", topic:"contract_security", type:"official_docs", authors:["Solidity Team"], year:2026, license:"GPL-3.0", status:"published", lastSyncedAt:"2026-08-13T09:10:00Z", collection:"official" },
  { id:"cosmos-ibc", title:"IBC Protocol Overview", url:"https://ibcprotocol.dev/", topic:"interoperability", type:"official_docs", authors:["Interchain Foundation"], year:2026, license:"Apache-2.0", status:"published", lastSyncedAt:"2026-08-13T09:20:00Z", collection:"official" },
  { id:"polkadot-xcm", title:"Polkadot XCM Documentation", url:"https://docs.polkadot.com/develop/interoperability/intro-to-xcm/", topic:"interoperability", type:"official_docs", authors:["Parity Technologies"], year:2026, license:"Apache-2.0", status:"published", lastSyncedAt:"2026-08-13T09:30:00Z", collection:"official" },
  { id:"chainlink-ccip", title:"Chainlink CCIP Architecture", url:"https://docs.chain.link/ccip/concepts/architecture", topic:"interoperability", type:"official_docs", authors:["Chainlink Labs"], year:2026, license:"Documentation", status:"published", lastSyncedAt:"2026-08-13T09:40:00Z", collection:"official" },
  { id:"hyperledger-fabric", title:"Hyperledger Fabric Documentation", url:"https://hyperledger-fabric.readthedocs.io/", topic:"foundation", type:"official_docs", authors:["Hyperledger Foundation"], year:2026, license:"Apache-2.0", status:"published", lastSyncedAt:"2026-08-13T09:50:00Z", collection:"official" },

  { id:"scengdl", title:"ScenGDL: Smart contract vulnerability detection and location based on temporal Scenarios and Graph convolution networks", url:"https://doi.org/10.1016/j.jss.2026.112898", topic:"lab", type:"paper", authors:["Xinyi Shen", "Xiangfu Zhao et al."], year:2026, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:00:00Z", doi:"10.1016/j.jss.2026.112898", abstract:"Temporal scenarios and graph convolution networks for smart-contract vulnerability detection and code-block localization.", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"llm-dependency-analysis", title:"Vulnerability detection of smart contracts by integrating large language models and dependency analysis", url:"https://doi.org/10.1016/j.engappai.2026.115511", topic:"lab", type:"paper", authors:["Jiarui Zhang", "Xiangfu Zhao", "Long He", "Tengfei Wang"], year:2026, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:01:00Z", doi:"10.1016/j.engappai.2026.115511", collection:"lab", orcid:"0000-0001-5870-5730", citedByCount:0, citationProvider:"Semantic Scholar" },
  { id:"flawcheck", title:"FlawCheck: Detecting Smart Contract Vulnerabilities Based on Symbolic Execution", url:"https://doi.org/10.1002/spy2.477", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2025, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:02:00Z", doi:"10.1002/spy2.477", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"ethereum-phishing-nas", title:"Phishing Detection on Ethereum via Graph Neural Architecture Search of Transaction Subgraph", url:"https://doi.org/10.1109/TCSS.2025.3570395", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2025, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:03:00Z", doi:"10.1109/TCSS.2025.3570395", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"csafuzzer", title:"CSAFuzzer: Fuzzing smart contracts combining with static analysis", url:"https://doi.org/10.1007/s10664-025-10623-3", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2025, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:04:00Z", doi:"10.1007/s10664-025-10623-3", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"tmf-net", title:"TMF-Net: Multimodal smart contract vulnerability detection based on multiscale transformer fusion", url:"https://doi.org/10.1016/j.inffus.2025.103189", topic:"lab", type:"paper", authors:["Tengfei Wang", "Xiangfu Zhao", "Jiarui Zhang"], year:2025, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:05:00Z", doi:"10.1016/j.inffus.2025.103189", collection:"lab", orcid:"0000-0001-5870-5730", citedByCount:13, citationProvider:"publisher" },
  { id:"reensat", title:"ReenSAT: Reentrancy Vulnerability Detection in Smart Contracts Using Semantic-Enhanced SAT Evaluation", url:"https://doi.org/10.1109/TR.2024.3488814", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2025, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:06:00Z", doi:"10.1109/TR.2024.3488814", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"contractgnn", title:"ContractGNN: Ethereum Smart Contract Vulnerability Detection Based on Vulnerability Sub-Graphs and Graph Neural Networks", url:"https://doi.org/10.1109/TNSE.2024.3470788", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2024, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:07:00Z", doi:"10.1109/TNSE.2024.3470788", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"parse", title:"ParSE: Efficient Detection of Smart Contract Vulnerabilities via Parallel and Simplified Symbolic Execution", url:"https://doi.org/10.1145/3639478.3643066", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2024, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:08:00Z", doi:"10.1145/3639478.3643066", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"da-gnn", title:"DA-GNN: A smart contract vulnerability detection method based on Dual Attention Graph Neural Network", url:"https://doi.org/10.1016/j.comnet.2024.110238", topic:"lab", type:"paper", authors:["Zixian Zhen", "Xiangfu Zhao", "Jinkai Zhang", "Yichen Wang", "Haiyue Chen"], year:2024, license:"Metadata and abstract", status:"published", lastSyncedAt:"2026-08-13T10:09:00Z", doi:"10.1016/j.comnet.2024.110238", collection:"lab", orcid:"0000-0001-5870-5730", citedByCount:69, citationProvider:"publisher" },
  { id:"msmart", title:"MSmart: Smart Contract Vulnerability Analysis and Improved Strategies Based on Smartcheck", url:"https://doi.org/10.3390/app13031733", topic:"lab", type:"paper", authors:["Xiangfu Zhao et al."], year:2023, license:"CC BY 4.0", status:"published", lastSyncedAt:"2026-08-13T10:10:00Z", doi:"10.3390/app13031733", collection:"lab", orcid:"0000-0001-5870-5730" },
  { id:"graphsa", title:"GraphSA: Smart Contract Vulnerability Detection Combining Graph Neural Networks and Static Analysis", url:"https://doi.org/10.3233/FAIA230374", topic:"lab", type:"paper", authors:["Long He", "Xiangfu Zhao", "Yichen Wang", "Jiahui Yang", "Xuelei Sun"], year:2023, license:"CC BY-NC 4.0", status:"published", lastSyncedAt:"2026-08-13T10:11:00Z", doi:"10.3233/FAIA230374", collection:"lab", orcid:"0000-0001-5870-5730" },

  { id:"oyente", title:"Making Smart Contracts Smarter", url:"https://doi.org/10.1145/2976749.2978309", topic:"contract_security", type:"paper", authors:["Loi Luu", "Duc-Hiep Chu", "Hrishi Olickel", "Prateek Saxena", "Aquinas Hobor"], year:2016, license:"Metadata and author manuscript", status:"published", lastSyncedAt:"2026-08-13T11:00:00Z", doi:"10.1145/2976749.2978309", collection:"high_impact", citedByCount:2216, citationProvider:"OpenAlex" },
  { id:"securify", title:"Securify: Practical Security Analysis of Smart Contracts", url:"https://doi.org/10.1145/3243734.3243780", topic:"contract_security", type:"paper", authors:["Petar Tsankov", "Andrei Dan", "Dana Drachsler-Cohen", "Arthur Gervais", "Florian Bünzli", "Martin Vechev"], year:2018, license:"Metadata and author manuscript", status:"published", lastSyncedAt:"2026-08-13T11:01:00Z", doi:"10.1145/3243734.3243780", collection:"high_impact" },
  { id:"maian", title:"Finding The Greedy, Prodigal, and Suicidal Contracts at Scale", url:"https://doi.org/10.1145/3274694.3274743", topic:"contract_security", type:"paper", authors:["Ivica Nikolić", "Aashish Kolluri", "Ilya Sergey", "Prateek Saxena", "Aquinas Hobor"], year:2018, license:"Metadata and author manuscript", status:"published", lastSyncedAt:"2026-08-13T11:02:00Z", doi:"10.1145/3274694.3274743", collection:"high_impact" },
  { id:"smartcheck", title:"SmartCheck: Static Analysis of Ethereum Smart Contracts", url:"https://doi.org/10.1109/WETSEB.2018.00012", topic:"contract_security", type:"paper", authors:["Sergei Tikhomirov et al."], year:2018, license:"Metadata", status:"published", lastSyncedAt:"2026-08-13T11:03:00Z", doi:"10.1109/WETSEB.2018.00012", collection:"high_impact" },
  { id:"gnn-ijcai", title:"Smart Contract Vulnerability Detection using Graph Neural Network", url:"https://www.ijcai.org/Proceedings/2020/454", topic:"contract_security", type:"paper", authors:["Yuan Zhuang", "Zhenguang Liu", "Peng Qian", "Qi Liu", "Xiang Wang", "Qinming He"], year:2020, license:"Open proceedings", status:"published", lastSyncedAt:"2026-08-13T11:04:00Z", doi:"10.24963/ijcai.2020/454", collection:"high_impact", citedByCount:450, citationProvider:"Semantic Scholar" },
  { id:"atomic-swaps", title:"Atomic Cross-Chain Swaps", url:"https://doi.org/10.1145/3212734.3212736", topic:"interoperability", type:"paper", authors:["Maurice Herlihy"], year:2018, license:"arXiv open manuscript", status:"published", lastSyncedAt:"2026-08-13T11:05:00Z", doi:"10.1145/3212734.3212736", collection:"high_impact", citedByCount:264, citationProvider:"publisher" },
  { id:"xclaim", title:"XCLAIM: Trustless, Interoperable, Cryptocurrency-Backed Assets", url:"https://doi.org/10.1109/SP.2019.00085", topic:"interoperability", type:"paper", authors:["Alexei Zamyatin et al."], year:2019, license:"Metadata and author manuscript", status:"published", lastSyncedAt:"2026-08-13T11:06:00Z", doi:"10.1109/SP.2019.00085", collection:"high_impact" },
  ...ORCID_ADDITIONAL_SOURCES,
];

export const DEMO_RESULTS: SearchResult[] = [
  { chunkId:"ibc-light-clients", sourceId:"cosmos-ibc", title:"IBC Protocol Overview", url:"https://ibcprotocol.dev/", section:"Light clients and consensus verification", snippet:"IBC uses on-chain light clients to verify consensus proofs from another chain. Relayers carry packets and proofs, but do not need to be trusted for correctness because invalid proofs fail verification.", topic:"interoperability", sourceType:"official_docs", year:2026, scores:{ vector:.91, keyword:.74, fusion:.88, rerank:.96 } },
  { chunkId:"xcm-consensus", sourceId:"polkadot-xcm", title:"Polkadot XCM Documentation", url:"https://docs.polkadot.com/develop/interoperability/intro-to-xcm/", section:"Cross-consensus messaging", snippet:"XCM defines a format for communicating intentions between consensus systems. Its execution and transport depend on the security relationship and message-passing protocol between those systems.", topic:"interoperability", sourceType:"official_docs", year:2026, scores:{ vector:.87, keyword:.61, fusion:.81, rerank:.89 } },
  { chunkId:"ccip-architecture", sourceId:"chainlink-ccip", title:"Chainlink CCIP Architecture", url:"https://docs.chain.link/ccip/concepts/architecture", section:"Decentralized oracle networks", snippet:"CCIP separates message execution and risk management, using independent oracle networks to observe source-chain events and authorize destination-chain execution.", topic:"interoperability", sourceType:"official_docs", year:2026, scores:{ vector:.81, keyword:.66, fusion:.78, rerank:.85 } },
  { chunkId:"solidity-reentrancy", sourceId:"solidity-security", title:"Solidity Security Considerations", url:"https://docs.soliditylang.org/en/latest/security-considerations.html#reentrancy", section:"Reentrancy", snippet:"Any interaction from a contract to another contract hands over control. A called contract may call back before the first interaction is complete, so state changes should precede external calls.", topic:"contract_security", sourceType:"official_docs", year:2026, scores:{ vector:.58, keyword:.20, fusion:.46, rerank:.31 } },
  { chunkId:"scengdl-method", sourceId:"scengdl", title:"ScenGDL", url:"https://doi.org/10.1016/j.jss.2026.112898", section:"Temporal scenarios and code-block localization", snippet:"ScenGDL models temporal execution scenarios and graph structure together, targeting both vulnerability detection and code-block-level localization rather than returning only a contract-level label.", topic:"lab", sourceType:"paper", year:2026, scores:{ vector:.89, keyword:.72, fusion:.86, rerank:.95 } },
  { chunkId:"da-gnn-method", sourceId:"da-gnn", title:"DA-GNN", url:"https://doi.org/10.1016/j.comnet.2024.110238", section:"Dual attention graph neural network", snippet:"DA-GNN combines graph representation with dual attention to emphasize vulnerability-relevant structural and semantic evidence; the published study evaluates the method on 17,670 real smart contracts.", topic:"lab", sourceType:"paper", year:2024, scores:{ vector:.84, keyword:.63, fusion:.80, rerank:.90 } },
  { chunkId:"graphsa-method", sourceId:"graphsa", title:"GraphSA", url:"https://doi.org/10.3233/FAIA230374", section:"Graph neural networks and static analysis", snippet:"GraphSA combines static-analysis signals with graph neural networks, providing an earlier laboratory baseline for learning vulnerability-related program structure.", topic:"lab", sourceType:"paper", year:2023, scores:{ vector:.78, keyword:.60, fusion:.75, rerank:.86 } },
  { chunkId:"oyente-symbolic", sourceId:"oyente", title:"Making Smart Contracts Smarter", url:"https://doi.org/10.1145/2976749.2978309", section:"Oyente symbolic execution", snippet:"Oyente introduced a symbolic-execution approach tailored to Ethereum bytecode and evaluated it on 19,366 deployed contracts, making it a foundational reference for automated smart-contract analysis.", topic:"contract_security", sourceType:"paper", year:2016, scores:{ vector:.77, keyword:.67, fusion:.76, rerank:.88 } },
  { chunkId:"gnn-ijcai-graph", sourceId:"gnn-ijcai", title:"Smart Contract Vulnerability Detection using Graph Neural Network", url:"https://www.ijcai.org/Proceedings/2020/454", section:"Contract graph learning", snippet:"The study represents smart contracts as graphs and applies graph neural networks to vulnerability detection, forming a widely cited bridge between program analysis and learned graph representations.", topic:"contract_security", sourceType:"paper", year:2020, scores:{ vector:.82, keyword:.64, fusion:.79, rerank:.91 } },
  { chunkId:"atomic-swaps-protocol", sourceId:"atomic-swaps", title:"Atomic Cross-Chain Swaps", url:"https://doi.org/10.1145/3212734.3212736", section:"Atomicity across blockchains", snippet:"Atomic cross-chain swaps formalize how multiple parties can exchange assets across distinct blockchains so that either every required transfer completes or none does.", topic:"interoperability", sourceType:"paper", year:2018, scores:{ vector:.85, keyword:.70, fusion:.83, rerank:.92 } },
];

export const EMPTY_EVALUATION: EvaluationRun = {
  version:"not-run", runAt:"", datasetSize:80,
  metrics:{ recallAt5:0, ndcgAt10:0, mrr:0, citationAccuracy:0, citationCoverage:0, faithfulness:0, refusalF1:0, searchP95Ms:0, generationP95Ms:0 },
  comparisons:[], state:"not_run", passed:false,
  notes:"真实语料索引与固定评测尚未完成，未展示演示指标。",
};
